export const cards = {
    copper: {
        name: "copper",
        type: "treasure",
        description: "",
        cost: 0,
        coins: 1,
        action: 0,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    silver: {
        name: "silver",
        type: "treasure",
        description: "",
        cost: 3,
        coins: 2,
        action: 0,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    gold: {
        name: "gold",
        type: "treasure",
        description: "",
        cost: 6,
        coins: 3,
        action: 0,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    estate: {
        name: "estate",
        type: "victory",
        description: "",
        cost: 2,
        coins: 0,
        action: 0,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    duchy: {
        name: "duchy",
        type: "victory",
        description: "",
        cost: 5,
        coins: 0,
        action: 0,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    province: {
        name: "province",
        type: "victory",
        description: "",
        cost: 8,
        coins: 0,
        action: 0,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    curse: {
        name: "curse",
        type: "curse",
        description: "-1 Victory Point",
        cost: 0,
        coins: 0,
        action: 0,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    cellar: {
        name: "cellar",
        type: "action",
        description: "Discard any number of cards, then draw that many.",
        cost: 2,
        coins: 0,
        action: 2,
        buy: 0,
        cards: 0,
        victory: 0,
    },
    moat: {
        name: "moat",
        type: "action - reaction",
        description: "When another player plays an Attack card, you may first reveal this from your hand, to be unaffected by it.",
        cost: 2,
        coins: 0,
        action: 0,
        buy: 0,
        cards: 2,
        victory: 0,
    },
};
