export const cards = {
    galactic_ice: {
        name: "Galactic Ice",
        type: "resource",
        description: "",
        cost: 0,
        coins: 1,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    silver: {
        name: "Mineral Deposit",
        type: "resource",
        description: "",
        cost: 3,
        coins: 2,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    gold: {
        name: "Antimatter",
        type: "resource",
        description: "",
        cost: 6,
        coins: 3,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    estate: {
        name: "estate",
        type: "influence",
        description: "",
        cost: 2,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    duchy: {
        name: "duchy",
        type: "influence",
        description: "",
        cost: 5,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    province: {
        name: "province",
        type: "influence",
        description: "",
        cost: 8,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    sabotage: {
        name: "sabotage",
        type: "sabotage",
        description: "-1 influence Point",
        cost: 0,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    cellar: {
        name: "cellar",
        type: "action",
        description: "Discard any number of cards, then draw that many.",
        cost: 2,
        coins: 0,
        actions: 1,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    moat: {
        name: "moat",
        type: "action - reaction",
        description: "When another player plays an Attack card, you may first reveal this from your hand, to be unaffected by it.",
        cost: 2,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 2,
        influence: 0,
    },
    village: {
        name: "village",
        type: "action",
        description: "Draw 1 card, +2 Actions.",
        cost: 3,
        coins: 0,
        actions: 2,
        buy: 0,
        cards: 1,
        influence: 0,
    },
    merchant: {
        name: "merchant",
        type: "action",
        description: "The first time you play a Silver this turn, +1 Coin.",
        cost: 3,
        coins: 1,
        actions: 1,
        buy: 0,
        cards: 1,
        influence: 0,
    },
    workshop: {
        name: "workshop",
        type: "action",
        description: "Gain a card costing up to 4.",
        cost: 3,
        coins: 4,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    smithy: {
        name: "smithy",
        type: "action",
        description: "Draw 3 cards.",
        cost: 4,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 3,
        influence: 0,
    },
    remodel: {
        name: "remodel",
        type: "action",
        description: "Trash a card from your hand. Gain a card costing up to 2 more than the trashed card.",
        cost: 4,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    militia: {
        name: "militia",
        type: "action",
        description: "Each other player discards down to 3 cards in hand.",
        cost: 4,
        coins: 2,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    market: {
        name: "market",
        type: "action",
        description: "",
        cost: 5,
        coins: 1,
        actions: 1,
        buy: 1,
        cards: 1,
        influence: 0,
    },
    mine: {
        name: "mine",
        type: "action",
        description: "Trash a resource from your hand. Gain a resource to your hand costing up to 3 more than it.",
        cost: 5,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },

};
