export const cards = {
    galactic_ice: {
        id: "galactic_ice",
        name: "Galactic Ice",
        type: "resource",
        description: "",
        cost: 0,
        coins: 1,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    mineral_deposit: {
        id: "mineral_deposit",
        name: "Mineral Deposit",
        type: "resource",
        description: "",
        cost: 3,
        coins: 2,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    antimatter: {
        id: "antimatter",
        name: "Antimatter",
        type: "resource",
        description: "",
        cost: 6,
        coins: 3,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    diplomatic_accord: {
        id: "diplomatic_accord",
        name: "Diplomatic Accord",
        type: "influence",
        description: "",
        cost: 2,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    military_conquest: {
        id: "military_conquest",
        name: "Military Conquest",
        type: "influence",
        description: "",
        cost: 5,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    economic_prosperity: {
        id: "economic_prosperity",
        name: "Economic Prosperity",
        type: "influence",
        description: "",
        cost: 8,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    galactic_unity: {
        id: "galactic_unity",
        name: "Galactic Unity",
        type: "influence",
        description: "",
        cost: 8,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    sabotage: {
        id: "sabotage",
        name: "sabotage",
        type: "sabotage",
        description: "-1 influence Point",
        cost: 0,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    refill_station: {
        id: "refill_station",
        name: "Refill Station",
        type: "action",
        description: "Discard any number of cards, then draw that many.",
        cost: 2,
        coins: 0,
        actions: 1,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    ionic_shield: {
        id: "ionic_shield",
        name: "Ionic Shield",
        type: "action - reaction",
        description: "When another player plays an Attack card, you may first reveal this from your hand, to be unaffected by it.",
        cost: 2,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 2,
        influence: 0,
    },
    space_colony: {
        id: "space_colony",
        name: "Space Colony",
        type: "action",
        description: "Draw 1 card, +2 Actions.",
        cost: 3,
        coins: 0,
        actions: 2,
        buy: 0,
        cards: 1,
        influence: 0,
    },
    rare_metal_merchant: {
        id: "rare_metal_merchant",
        name: "Rare Metal Merchant",
        type: "action",
        description: "The first time you play a Silver this turn, +1 Coin.",
        cost: 3,
        coins: 1,
        actions: 1,
        buy: 0,
        cards: 1,
        influence: 0,
    },
    mechanic_bay: {
        id: "mechanic_bay",
        name: "Mechanic Bay",
        type: "action",
        description: "Gain a card costing up to 4.",
        cost: 3,
        coins: 4,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    threed_printing_array: {
        id: "threed_printing_array",
        name: "3d Printing Array",
        type: "action",
        description: "Draw 3 cards.",
        cost: 4,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 3,
        influence: 0,
    },
    ship_upgrades: {
        id: "ship_upgrades",
        name: "Ship Upgrades",
        type: "action",
        description: "Trash a card from your hand. Gain a card costing up to 2 more than the trashed card.",
        cost: 4,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    cargo_pirates: {
        id: "cargo_pirates",
        name: "Cargo Pirates",
        type: "action",
        description: "Each other player discards down to 3 cards in hand.",
        cost: 4,
        coins: 2,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    },
    galactic_trading_post: {
        id: "galactic_trading_post",
        name: "Galactic Trading Post",
        type: "action",
        description: "",
        cost: 5,
        coins: 1,
        actions: 1,
        buy: 1,
        cards: 1,
        influence: 0,
    },
    asteroid_mine: {
        id: "asteroid_mine",
        name: "Asteroid Mine",
        type: "action",
        description: "Trash a resource from your hand. Gain a resource to your hand costing up to 3 more than it.",
        cost: 5,
        coins: 0,
        actions: 0,
        buy: 0,
        cards: 0,
        influence: 0,
    }
};
